"""update user document

Revision ID: 5027637138fe
Revises: a3f16b4e59fe
Create Date: 2025-10-04 16:37:21.448608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5027637138fe'
down_revision: Union[str, Sequence[str], None] = 'a3f16b4e59fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_knowledge_base_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'knowledge_base', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_knowledge_base_id_fkey'), 'document', 'document', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###
