"""delete relationship user with tables other

Revision ID: c03de6058aa8
Revises: 288b9ae0bbc9
Create Date: 2025-10-07 14:51:51.177922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c03de6058aa8'
down_revision: Union[str, Sequence[str], None] = '288b9ae0bbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('chat_user_id_fkey'), 'chat', type_='foreignkey')
    op.drop_column('chat', 'user_id')
    op.add_column('chunk', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('chunk_user_id_fkey'), 'chunk', type_='foreignkey')
    op.drop_column('chunk', 'user_id')
    op.add_column('document', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('document_user_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'user_id')
    op.add_column('embedding', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('embedding_user_id_fkey'), 'embedding', type_='foreignkey')
    op.drop_column('embedding', 'user_id')
    op.add_column('knowledge_base', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('knowledge_base_user_id_fkey'), 'knowledge_base', type_='foreignkey')
    op.drop_column('knowledge_base', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('knowledge_base_user_id_fkey'), 'knowledge_base', 'user', ['user_id'], ['id'])
    op.drop_column('knowledge_base', 'username')
    op.add_column('embedding', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('embedding_user_id_fkey'), 'embedding', 'user', ['user_id'], ['id'])
    op.drop_column('embedding', 'username')
    op.add_column('document', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('document_user_id_fkey'), 'document', 'user', ['user_id'], ['id'])
    op.drop_column('document', 'username')
    op.add_column('chunk', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chunk_user_id_fkey'), 'chunk', 'user', ['user_id'], ['id'])
    op.drop_column('chunk', 'username')
    op.add_column('chat', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chat_user_id_fkey'), 'chat', 'user', ['user_id'], ['id'])
    op.drop_column('chat', 'username')
    # ### end Alembic commands ###
