"""update document table

Revision ID: e2c95b35b391
Revises: 02e42f982e10
Create Date: 2025-10-04 16:28:52.047701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2c95b35b391'
down_revision: Union[str, Sequence[str], None] = '02e42f982e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('knowledge_base_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'document', 'document', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'knowledge_base_id')
    # ### end Alembic commands ###
