"""create metadata table for upload file

Revision ID: f0769256bbba
Revises: 73da50354e90
Create Date: 2025-09-13 23:45:28.754293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0769256bbba'
down_revision: Union[str, Sequence[str], None] = '73da50354e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemetadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename_original', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename_saved', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filemetadata')
    # ### end Alembic commands ###
